### ISSUE TITLE
no release asset and compile failed！

### ISSUE THREAD

**Issue by whiteskylife** [sjqzhang/ops_channel#1]
https://github.com/sjqzhang/ops_channel/releases/download/v1.0/CliServer   not found !

get compile err below
go build -o CliServer main.go
# command-line-arguments
.\main.go:181:17: too many arguments in call to cron.New
.\main.go:181:18: undefined: cron.WithParser
.\main.go:181:49: undefined: cron.WithChain
.\main.go:3828:12: cronTab.Remove undefined (type *cron.Cron has no field or method Remove)
.\main.go:3828:25: entry.ID undefined (type *cron.Entry has no field or method ID)
.\main.go:3862:12: cronTab.Remove undefined (type *cron.Cron has no field or method Remove)
.\main.go:3862:20: undefined: cron.EntryID
.\main.go:3867:12: cronTab.Remove undefined (type *cron.Cron has no field or method Remove)
.\main.go:3867:20: undefined: cron.EntryID
.\main.go:3876:13: cronTab.Remove undefined (type *cron.Cron has no field or method Remove)
.\main.go:3876:13: too many errors

**Comment by sjqzhang** [comment]
使用本地vendor进行构建。
